on:
    release:
      types: [published]
  
  
jobs:
    pypi-publish:
      name: upload release to PyPI
      runs-on: ubuntu-latest
      environment:
          name: Prod
          url: https://pypi.org/p/cube-utils
      permissions:
        # This permission is needed for private repositories.
        contents: read
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
      steps:
        - uses: actions/checkout@v4
  
        # Install PDM
        - name: Install PDM
          run: python -m pip install --upgrade pip pdm

        # Install build dependencies
        - name: Install build dependencies
          run: pdm install --prod

        # Build the package
        - name: Build package
          run: pdm build

        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1

    npm-publish:
      name: upload release to npm
      runs-on: ubuntu-latest
      environment:
        name: Prod
      permissions:
        contents: read
        id-token: write
      steps:
        - uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'
            registry-url: 'https://registry.npmjs.org'

        - name: Install JavaScript dependencies
          working-directory: ./cube-utils-js
          run: npm install

        - name: Run JavaScript tests
          working-directory: ./cube-utils-js
          run: npm test

        - name: Publish package to npm
          working-directory: ./cube-utils-js
          run: npm publish --provenance --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
